Include JSR305 in jar, SpongeAPI requires it for javax.annotation.Nullable at runtime
Fixes com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/annotation/Nullable
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at net.glowstone.shiny.event.GraniteEventFactory.createStateEvent(GraniteEventFactory.java:65)
	at net.glowstone.shiny.Shiny.postState(Shiny.java:63)
	at net.glowstone.shiny.Shiny.load(Shiny.java:54)
	at net.glowstone.GlowServer.start(GlowServer.java:455)
	at net.glowstone.GlowServer.main(GlowServer.java:108)